plugins/ROS/shape_shifter_factory.hpp

This looks like a great project.
I just had a small error when compiling.
This std::__cxx11::string probably just slipped in through auto-complete, since it is used nowhere else.
Removing it made it compile for me on Ubuntu 14.04 with gcc 4.8.4.

fix small autocomplete typo

---

plotter_gui/mainwindow.cpp

For some reason the main window's menu bar does not show up on Ubuntu 14.04 using Gnome Flashback Session.
Adding a simple show() call makes it work...

Main Menu fix

---

CMakeLists.txt

Adding STATUS to the message will still show it with a manual make but will not be seen by the catkin build system as a warning.

Prevent compiler warning if compiling under ROS

---

plugins/ROS/RosoutPublisher/logs_table_model.cpp
plugins/ROS/RosoutPublisher/modelfilter.cpp

These are just fixes so it doesn't display build warnings, feel free to change them or print errors where they need to be printed.

Add dummy returns to function that required it

---

docs/tracker.md
include/PlotJuggler/random_color.h

pj-tracker.png was removed in last documentation upgrade, so I guess PlotJuggler_tracker.png wants to be linked instead (at least for the moment).

Fix image link in tracker.md

---

plotter_gui/plotwidget.cpp

Adding time_offset (which can be a very large number) to the left and right time end points of a data series, we can have precision issues causing errors of the type "invalid X0/X1 range in PlotWidget::maximumRangeY". To prevent this, we shift the left and right values slightly after adding the time_offset so that they are still in the expected range.

Potential fix for precision issue when adding time_offset

---

backward-cpp/backward.hpp
plugins/DataLoadCSV/CMakeLists.txt
plugins/DataStreamSample/CMakeLists.txt

Mainly caused by newer versions of Qt5 and Glibc. I think these changes are safe even for older versions.

Fix build failures on Archlinux

---

plotter_gui/filterablelistwidget.cpp
plotter_gui/filterablelistwidget.h

If you have a list with multiple elements:
ABAR
FOO
ZBAR
And you filter by "BAR" you'll get a list of two elements, but if you shift-click on the first and the last, "FOO" will be selected as well, even though it's hidden. 
This patch should prevent FOO from being drag&dropped into the curve display and being deleted if it's hidden.

Fix dragging/deletion of hidden items

---

CMakeLists.txt
plotter_gui/mainwindow.cpp

Fixes the build on MacOS, an extra qt path is added to the search path when cmake is run on an apple OS.

CMakeLists.txt add mac homebrew qt5 install directory

---

plotter_gui/tabbedplotwidget.cpp

This helps when saving multiple images of tabs.

Make default filename for tab image the tab name.

---

plotter_gui/mainwindow.cpp
plotter_gui/mainwindow.h
plotter_gui/mainwindow.ui
plotter_gui/tabbedplotwidget.cpp
plotter_gui/tabbedplotwidget.h

Extends https://github.com/facontidavide/PlotJuggler/pull/136 and closes #128 allowing a user to save all tabs as images in a selected folder.

Save all tab plots as images in a folder.

---

plugins/DataStreamWebSocket/DataStreamClientSample/client.cpp

Note that I am not sure if the `Windows` include is really needed in this file...
But I do not have a Windows machine to test.

Allow to build the DataStreamClientSample on Linux

---

plugins/DataLoadULog/ulog_parser.cpp

**Problem**
I was not able to open log files which included arrays of nested topics. I think I found the cause why this was not working, however, the data of the nested topics is still not displayed correctly. There seems to be a miss-alignment between labels and data (only for that nested topic).
Unfortunately, I'm currently not able to share a log file that includes nested topics. (The one I was using was from a customer and I cannot share it here :-( ).
I will try to look for a public log. In my case the vehicle was logging the "esc_status" message which contains an array of "esc_report" message.
This is the error message that I saw when trying to parse the log file:
With this PR the log file is parsed and the message label appear, however, the data is not correct yet.
In the plot …

ulog_parser: fixed parsing of array topics

---

plotter_gui/plotwidget.cpp

On MacOS there are several mime formats generated in addition to "curveslist", this fix will keep curves array with names collected instead of resetting it for each new mime format.

Make drag-drop work on MacOS

---

plotter_gui/mainwindow.cpp

Fixes #155 
The name of the new image is `2019-03-21_10-41-22_01_plot.png` for example.

Use yyyy-MM-dd_HH-mm-ss name when saving a plot as image

---

backward-cpp/README.md

That's it all! Two small typos in the markup for two titles in the README.md file

Fixed small typos in README.md

---

plotter_gui/mainwindow.cpp

Sometimes it is usefull to have a view of streaming on a longer duration. This PR allow to have unlimited buffer when streaming. 
When spinbox value is set to maximum, buffer is switch to infinite size. Color is switch to red to remember possible memory limits issue.

No duration limit on buffer

---

plotter_gui/transforms/custom_function.cpp

This Pr fix a possible invalid data access with back() on empty vector.
This could be triggered when used custom function in layout and stream in simulation (when layout is load before bag streaming start).

Read out of array

---

plotter_gui/mainwindow.cpp
plotter_gui/transforms/function_editor.cpp
plugins/ROS/RosMsgParsers/ros_parser.cpp

Three small fix:
1. the ref topic in custom function, could be change by the editor if this topic does not exist/is not loaded yet. The first commit add the ref in the combo box if not present.
2. the deleteDataMultipleCurves make a return if a curve if not found, I thinks it is more a continue here. As every curve should be deleted
3. the RosMessageParser::registerSchema did not return a value. This produce big mess with the optimiser ....
Also just as a side note:
the _builtin_parsers parsers objects are never deleted and I don't think they are automatic object.
https://github.com/facontidavide/PlotJuggler/blob/ace1da563ba09ce2363a08ec4e254a9c644bf498/plugins/ROS/RosMsgParsers/ros_parser.cpp#L19 
https://github.com/facontidavide/PlotJuggler/blob/ace1da563ba09ce2363a08ec4e254a9c644bf498/p …

Minor fixes

---

plugins/ROS/DataLoadROS/dataload_ros.cpp

* previous behaviour: the bag load was aborted
* with this patch: prompt user whether or not to
* skip this problematic topic and continue loading
* skip this and other problematic topics that may arise when loading
* abort the load
The patch addresses a real life example when some of the ros messages are created
from ROS-matlab, and therefore suffers from a bug related to a bad message description
E.g. see https://github.com/rosjava/rosjava_bootstrap/issues/16

Prompt user when one or more topics in the rosbag cannot be loaded

---

plotter_gui/plotwidget.cpp

A fix for a bug on archlinux, a segfault append when I try to swap two plot widgets.
It is not yet visible on ubuntu but it's just a matter of time...
This bug is introduced in: 7959e54 Spurious DragLeave fixed?
And produce a segfault(nullptr) in QCursor::shape() call by
QBasicDrag::updateCursor(Qt::DropAction) [trigger by plotwidget.cpp:1352
drag->exec();].
It seems to me that the change of global application cursor on leave event during drag drop
operation cause the problem [is it the drop widget duty to reset cursor?].
Full stack trace:
"""
Stack trace (most recent call last):
#31   Object "/usr/lib/libQt5Widgets.so.5", at 0x7f8e9a5213c0, in QApplication::notify(QObject*, QEvent*)
#30   Object "/usr/lib/libQt5Widgets.so.5", at 0x7f8e9a519da3, in …

Fix segfault when swap plotwidget on archlinux (qt5.12.3).

---

plugins/ROS/qnodedialog.cpp

If multiple plotjuggler instance are running at the same time, only one could have a working data stream topic.

data stream topic plugin

---

CMakeLists.txt
package.xml
plugins/ROS/TopicPublisherROS/statepublisher_rostopic.cpp

I had a compilation error that turned out to be related with an old version of `abseil_cpp`, but I found out that `PlotJuggler` didn't depend on `abseil_cpp`. This simply adds the missed dependency and also one missed header, although for it compiles find w/o this PR at the end.

Add missed abseil_cpp depend

---

plugins/ROS/RosMsgParsers/ros_parser.cpp

This closes #207 by adding the requested cast.

RosMsgParsers: add cast to be clang compatible

---

plotter_gui/mainwindow.ui

The shortcut F10 to toggle fullscreen is not working anymore.
An action is defined in the main_window.ui file and a qt shortcut is defined in the main_window.cpp:
https://github.com/facontidavide/PlotJuggler/blob/ac8460c78f6379ad6b51c84226000789bb160ad0/plotter_gui/mainwindow.cpp#L52
At the moment using the action is not working (could not leave fullscreen mode with the action : is it a focus problem ?). So, the simple fix is to keep hard-coded shortcut in cpp....

Fix F10 is ambiguous

---

plotter_gui/plotwidget.cpp

A small change that did not take into account the invisible curve when compute the limit on x and y axis.
It also zoom out on x axis when visibility change is triggered.

Dont take invisible curve into account for axis limit computation

---

plotter_gui/curvelist_panel.h

Using Mac OS X to compile on the current main branch will output the following error
```
[  1%] Built target fmt
[  2%] Automatic MOC and UIC for target colorwidgets
[  2%] Built target colorwidgets_autogen
[  6%] Built target colorwidgets
[  7%] Automatic MOC and UIC for target marl
[  7%] Built target marl_autogen
[ 16%] Built target marl
[ 17%] Automatic MOC and UIC for target qwt_static
[ 17%] Built target qwt_static_autogen
[ 65%] Built target qwt_static
[ 66%] Automatic MOC and UIC for target PlotJuggler
[ 66%] Built target PlotJuggler_autogen
Scanning dependencies of target PlotJuggler
[ 67%] Building CXX object plotter_gui/CMakeFiles/PlotJuggler.dir/PlotJuggler_autogen/mocs_compilation.cpp.o
In file included from /Users/xiaowei/src/PlotJuggler/build/plotter_gui/PlotJuggler_autogen/ …
```

add include array header file to fix MAC OS X build error

---

plugins/ROS/RosMsgParsers/pal_statistics_msg.h

Otherwise the time order may not be respected and the data is loaded
incorrectly
Load the following bag and check the foo, bar and bar1 variables.
Using the ordered map is only valid as long as the `names_version` field is always incremental (which it is) but I guess we should order by data timestamp to be 100% correct.
[demo.tar.gz](https://github.com/facontidavide/PlotJuggler/files/4122716/demo.tar.gz)

Use ordered map, appendData needs to insert data in order

---

plugins/DataLoadULog/ulog_parser.cpp

Silences:
```
Warnings   << plotjuggler:make /home/administrator/ortools_ws/logs/plotjuggler/build.make.000.log
/home/administrator/ortools_ws/src/PlotJuggler/plugins/DataLoadULog/ulog_parser.cpp: In lambda function:
/home/administrator/ortools_ws/src/PlotJuggler/plugins/DataLoadULog/ulog_parser.cpp:784:27: warning: ‘%02d’ directive writing between 2 and 10 bytes into a region of size 9  -Wformat-overflow=]
784 |           sprintf(buff, ".%02d", i);
|                           ^~~~
/home/administrator/ortools_ws/src/PlotJuggler/plugins/DataLoadULog/ulog_parser.cpp:784:25: note: directive argument in the range [0, 2147483647]
784 |           sprintf(buff, ".%02d", i);
|                         ^~~~~~~
In file included from /usr/include/stdio.h:867,
from /usr/include/c++/9/cstdio:42,
from …
```

Fix another sprintf buffer size warning

---

CMakeLists.txt
package.xml
plugins/ROS/CMakeLists.txt

Resolves #304 / #306 , allows PlotJuggler to be built from source and run on ROS2 eloquent.

build fixes to work on ROS2 eloquent

---

plugins/ROS/ros1_parsers/pal_statistics_msg.h

- Allow display of multiple pal_statistics_msg topics with same version
- Remove "values/" from pal_statistics variable names
The second change is cosmetic, but saves some screen space which is always nice.

pal_statistics fixes

---

CMakeLists.txt
plugins/DataStreamUDP/CMakeLists.txt

Otherwise build fails for me on OSX with linking errors.

Add required Qt5::Network for DataStreamUDP

---

src/curvelist_view.h

MSVC fails to compile `SortedTableItem<QTreeWidgetItem>`.
If we use that definition, the class QTreeWidgetItem becomes a baseclass of SortedTableItem. That also inherits an enum called "ItemType" (which is the same as the template name). MSVC stumbles and spits out compilation errors :facepalm: . A simple solution is to rename the template parameter :facepalm: :facepalm:

Template parameter named ItemType collides with enum called ItemType

---

3rdparty/Qt-Advanced-Docking/CMakeLists.txt

See https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/src/CMakeLists.txt#L52
Fix #353

Do not compile FloatingWidgetTitleBar on OSX

---

CMakeLists.txt
src/plotwidget.cpp

This PR has been created for visibility with regards to #368 and may be merged if desired, or inspected by others curious about running 3.0.x on windows.
As mentioned there, this does not include LSL plugin support, but it does enable the windows build to run under basic functionality. I have not tested UDP streaming or plugins outside DataLoaders (csv and a plugin for a custom format). However, based on the testing I did perform, I did not notice any issues.
For building, I mirrored the environment described in #315.

Enable use on Windows for 3.0.x

---

3rdparty/backward-cpp/backward.hpp

backward-cpp dependency fix for ARM 64 backport, wrong access to PC register.

Apple Mac M1 build fix.

---

src/plotwidget.cpp

**Issue**: The xy-curves had always red symbols as markers, which gets a bit confusing if there are multiple curves in one widget.
**Changes**: 
1. Marker color is now set the line color (either automatically assigned if line is added or to the newly selected color in plotwidget_editor)
2. Additionally, removed the tracker redrawing in xmlLoad since this resulted in ghost-markers at the origin which should be there. I was not so sure about this, but I tested it and it appears to be the fix for it

XY curve markers: fixed colors and removed ghosts symbols

---

README.md

This patch is to fix the issues mentioned in #417 .

Add libqt5x11extras5-dev into installation guide for fedora/ubuntu.

---

src/mainwindow.cpp

Fairly straight forward. There's two typos in the prompt for loading transformations :)

Fix typo in "load transformations" prompt

---

plugins/DataLoadULog/ulog_messages.h
plugins/DataLoadULog/ulog_parser.cpp

From https://github.com/PX4/PX4-user_guide/pull/1103
And updates the header to the latest PX4 version.
Is there a style fix script?

ulog: ignore parameter default message

---

CMakeLists.txt

Fix typo when building without ROS support

---

plotjuggler_app/resources/default.snippets.xml

@facontidavide This have been really useful to me in the past to inspect PX4 (`.ulg`) logs and will be really useful to other users. Instead of having to share a `.xml` gist to everyone, I'm wondering if you would be OK to add these functions to the default snippet set.
Summary:
Add 3 functions to convert a Hamiltonian attitude quaternion to its Euler (Tait-Bryan 321/yaw-pitch-roll) representation
Result:

Add quaternion to Euler conversion snippets

---

plotjuggler_app/mainwindow.cpp
plotjuggler_app/preferences_dialog.cpp
plotjuggler_app/preferences_dialog.h

Fixed wrong slot name on PreferencesDialog and moved skin-based setting of MainWindowTitle after the setupUi() call

Fixed small issues with PreferencesDialog and use of skin to set the main window title 

---

README.md

To compile the Protobuf parser plugin I needed to install  libprotoc-dev on Ubuntu 20.04, so it might be useful to note this in the Readme.md

Added libprotoc-dev to the apt install package list

---

plotjuggler_plugins/ToolboxLuaEditor/lua_editor.ui

While trying to use the new ReactiveLuaFunction, I came across of what I think is a typo. I will try to propose more examples for custom functions.

Fix typo in toolbox Lua

---

CMakeLists.txt
plotjuggler_app/nlohmann_parsers.cpp
plotjuggler_app/nlohmann_parsers.h
plotjuggler_plugins/DataStreamZMQ/CMakeLists.txt

I modified the checkbox in streaming plugins to use timestamp field, so that it can use a different field. This is useful to me and I only tested with UDP and ZeroMQ. Using a field with bogus data as timestamp can cause buggy behavior, but that's probably some core function I'm not sure I have the ability to fix.

Timestampfield

---

README.md

To make it easy for everybody to just copy the command and install the PlotJuggler, ROS has the version name, kinetic, melodic ... etc., in its environmental variable $ROS_DISTRO. Also, the name is self-explanatory for someone new to ROS who needs to substitute with the required ROS distribution name. This modification will at least try to make it easier for somebody who already has the right environment to install PlotJuggler.

Modify install command to make it easier to install PlotJuggler

---

.github/workflows/ros2.yaml
CMakeLists.txt
plotjuggler_app/CMakeLists.txt

These changes should resolve the rolling build on Ubuntu Jammy https://build.ros2.org/view/Rbin_uJ64/job/Rbin_uJ64__plotjuggler__ubuntu_jammy_amd64__binary/
Also adds a Rolling CI.

Passing CI on ROS2 Rolling

---

CMakeLists.txt

add STATUS to CmakeLists.txt message() to avoid 'message called with incorrect number of arguments'

---

plotjuggler_plugins/DataLoadCSV/dataload_csv.ui

Set openExternalLinks property of label_4 in dataload_csv to true to allow the hyperlink to open in a web browser when clicked

Make link open in browser when clicked

---

plotjuggler_plugins/ToolboxLuaEditor/lua_editor.ui

Similar to https://github.com/facontidavide/PlotJuggler/pull/658 but applied to the tutorial link in the reactive lua editor

Make tutorial link open in browser when clicked

---

plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp
plotjuggler_plugins/DataLoadCSV/dataload_csv.ui

minor change to CSV loader to allow the cancel button to always be enabled. Previously the cancel button was enabled/disabled with the Ok button

fix Cancel button in CSV loader

---

plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp

Previously the CSV dataload plugin was not saving the correct XML state
when a generated time axis was used.

Fix CSV generated time axis.

---

plotjuggler_plugins/ToolboxLuaEditor/lua_editor.ui

Fix typo in reactive script editor

---

plotjuggler_plugins/DataLoadCSV/CMakeLists.txt
plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp
plotjuggler_plugins/DataLoadCSV/dataload_csv.ui

Promote the rawText widget in csv loader to QCodeEditor for line number display and set the widget theme to be consistent with the Lua script editor (no syntax highlighting)

Add line numbers to csv loader

---

plotjuggler_plugins/StatePublisherCSV/publisher_csv_dialog.ui

-Add tooltips to the buttons that set the start/end time based on vertical time tracker position
-add missing space in text ("timerange" to "time range")
(added space to "timerange" not shown in image above)

Add tooltips to CSV publisher buttons

---

plotjuggler_plugins/StatePublisherCSV/publisher_csv.cpp

Fix bug with the csv publisher where clicking buttonGetStart or buttonGetEnd buttons would override the checkBoxFirst/checkBoxLast selections
~~Fixed by enabling/disabling the buttons when the checkboxes are toggled~~
**Edit:** fixed by unchecking the first/last checkboxes when the button is pressed. This seems less of an annoyance where a user may move the cursor and want to set the time and not notice that the first/last checkbox is checked

Fix start/end time bug in CSV Exporter

---

3rdparty/QCodeEditor/CMakeLists.txt
3rdparty/QCodeEditor/include/QCSVHighlighter
3rdparty/QCodeEditor/include/internal/QCSVHighlighter.hpp
3rdparty/QCodeEditor/src/internal/QCSVHighlighter.cpp
plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp
plotjuggler_plugins/DataLoadCSV/dataload_csv.h
plotjuggler_plugins/DataLoadCSV/dataload_csv.ui

**CSV Table Preview**
-CSV data loader updated with new table view widget for file preview
-Table view updates when user changes delimiter
-Tab widget added to the CSV data loader to switch between raw text view and table view
https://user-images.githubusercontent.com/2954254/177014679-7dbf53e0-b374-4d22-adb5-0862a1d23c37.mp4
**CSV Highlighting**
-Add QCSVHighlighter to apply syntax highlighting to the selected delimiter in the csv raw text preview
-Highlighting updates when user changes delimiter

Add CSV table preview and CSV highlighting

---

plotjuggler_plugins/DataStreamMQTT/datastream_mqtt.h

In mqtt_plugin, std::thread is being utilized, but instead QThread is being included. This results in include problems on my setup (Ubuntu 18.04) on source builds (an sample error in below). The minor change proposed resolves the include problems in my setup.
```
PlotJuggler/plotjuggler_plugins/DataStreamMQTT/datastream_mqtt.h:53:8: error: ‘thread’ in namespace ‘std’ does not name a type
std::thread _mqtt_thread;
```

Fix minor include problem for mqtt_plugin

---

plotjuggler_app/plot_docker.cpp
plotjuggler_app/plot_docker_toolbar.cpp
plotjuggler_app/plot_docker_toolbar.h
plotjuggler_app/plotwidget.cpp
plotjuggler_app/plotwidget.h
plotjuggler_app/resources/stylesheet_dark.qss
plotjuggler_app/resources/stylesheet_light.qss
plotjuggler_app/statistics_dialog.cpp
plotjuggler_app/statistics_dialog.h
plotjuggler_app/statistics_dialog.ui

Changes and bug fixes to the statistics dialog window
Improvements:
- Statistics can now be calculated from the visible range or by the full data range (previously only visible range)
- Statistics window title now includes the title from the plot
- Made the dialog window stay on top of the PlotJuggler window but not on top of other programs. The statistics dialogs will minimize/restore with the main PJ window. Previously the statistics dialog windows would stay on top of all windows
- ~~Made the table sortable by column (click on the header item to sort by that column)~~  (**Edit:** disabled this as there are bugs. earlier commit kept as it set the styling for the arrows)
Bug fixes:
- Fix bug where statistics would only get updated for the plot with the mouse over it when zooming while …

Statistics dialog improvements and bug fixes

---

plotjuggler_app/plotwidget.cpp
plotjuggler_app/plotwidget.h
plotjuggler_app/plotwidget_transforms.cpp
plotjuggler_app/preferences_dialog.cpp
plotjuggler_app/preferences_dialog.ui
plotjuggler_app/resources/stylesheet_dark.qss
plotjuggler_app/resources/stylesheet_light.qss
plotjuggler_base/src/plotwidget_base.cpp

New tab added to preferences for configuring autozoom settings:
Defaults are enabled which preserve the original PlotJuggler behavior
Addresses https://github.com/facontidavide/PlotJuggler/issues/654

Add options for enabling/disabling autozoom in preferences

---

snap/snapcraft.yaml

From this comment: https://github.com/facontidavide/PlotJuggler/pull/714#issuecomment-1206335503
We realized that releasing the snap to a stable branch wasn't working.
The `grade` was programmatically set during the pull of the PlotJuggler part. But the YAML was also setting the `grade`.
And the YAML file has the priority: https://github.com/facontidavide/PlotJuggler/runs/7689122227?check_suite_focus=true#step:3:14109
Removing the `grade` from the YAML solves the problem.
Sorry for the inconvenience.

fix(snap): remove yaml grade

---

plotjuggler_app/plotwidget.cpp
plotjuggler_app/plotwidget.h
plotjuggler_app/tabbedplotwidget.cpp
plotjuggler_base/include/PlotJuggler/plotwidget_base.h
plotjuggler_base/src/plotwidget_base.cpp

- Plot widgets were not clearing their drag and drop state if a drag event left the widget, causing mouse events to not be handled properly if the drop event happened in another plot widget
- Added event handlers for drag leave event
(This was actually a pain to debug at first because it seemed like it was only impacting the first plot widget that existed, but it was just unfortunate that I was really repeatably dragging across the same widget)

Fix plot widget drag and drop bug (Issue #716)

---

plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp
plotjuggler_plugins/DataLoadCSV/dataload_csv.h

**Summary**
- Allow PlotJuggler to load CSV files with non-monotonic data with a warning (data is sorted to be monotonic) instead of aborting
- Improvements to error handling dialogs with additional information 
**Handling Non-Monotonic data**
The csv loader would reject csv files that didn't have the data sorted strictly monotonically and would abort loading the file if this was detected. This isn't necessary as the push_back() function used to add the data in the TimeseriesBase class already detects this and inserts new values into the correct place. Since non-monotonic time might be unexpected by the user this change brings up a dialog window where the user can choose to abort or continue with extra information that can be viewed:
**Other Improvements**
These are mostly quality of life …

Improve CSV loader error handling

---

README.md

Update the readme with details on how to switch between ROS & ROS 2 for the default plotjuggler snap command.

readme: add details about default snap command

---

plotjuggler_app/mainwindow.cpp

Broken in #726. If all plugins are enabled, then opening a file supported by multiple plugins does not work.

Fix multi-plugin selection

---

COMPILE.md

Hey,
I've noticed that on the fresh OS install the cmake is also missing.
This pr fixes it.

compile: add cmake to brew install

---

plotjuggler_plugins/StatePublisherCSV/publisher_csv.cpp

With geographic coordinates, the precision is critical to get centimeter accuracy.
On the following image in QGis, le red dots have a precision of 6 and the blue ones have a precision of 9 digits.
For reference, the red rectangle has a width of 2 m.
According to [this answer](https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude/8674#8674), 8 digits should be enough already but I have used 9 as a multiple of 3. But I can change it if you wish.

Add precision to CSV export to handle geocoordinates

---

plotjuggler_plugins/ParserROS/rosx_introspection/include/rosx_introspection/details/conversion_impl.hpp

Fixing what I assume is a typo in the code that I noticed while looking at other things. I didn't see `checkUpperLimitFloat` used anywhere else so I assume it was meant to be here.

[bugfix] conversion typo?

---

plotjuggler_plugins/DataStreamMQTT/datastream_mqtt.cpp

The MQTT data streamer in plot juggler currently does not use the MQTT topic name when creating parsers. If/when #745 is merged, this becomes a larger issue as data from multiple different topics becomes merged together. If different MQTT topics contain fields of the same name, then it is next to impossible to differentiate them in PJ. This change allows the topic name to be reflected in the tree view when selecting data and makes the data fields easily distinguishable.

Always use topic names for creating MQTT parsers

---

plotjuggler_plugins/DataStreamMQTT/datastream_mqtt.ui

PlotJuggler has become an integral part of our workflow for testing our system. Previous version of PJ allowed you to subscribe to multiple MQTT topics, but since the change to the mosquito-based MQTT plugin, this is no longer possible. This change fixes that and allows us to plot data from multiple topics once more.

Set MQTT topics list to be multi-selectable

---

plotjuggler_plugins/DataLoadCSV/CMakeLists.txt
plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp
plotjuggler_plugins/DataLoadCSV/dataload_csv.h
plotjuggler_plugins/DataLoadCSV/dataload_csv.ui
plotjuggler_plugins/DataLoadCSV/datetimehelp.cpp
plotjuggler_plugins/DataLoadCSV/datetimehelp.h
plotjuggler_plugins/DataLoadCSV/datetimehelp.ui

Added a new dialog window to the CSV loader to help with the date time format strings.
**Features:**
-Date time format string preview: displays the result from a given format string for a user-specified date time
-Checkbox at the bottom to allow the help dialog to stay open when opening multiple csv files
The dialog can be opened by clicking on the new "Date Format Help" button that replaces the old message with hyperlink to the Qt documentation

Add CSV loader date-time format help dialog

---

plotjuggler_plugins/ParserROS/rosx_introspection/src/ros_message.cpp

In the latest PlotJuggler I'm failing to decode some messages with the following error: `throw std::runtime_error("Missing ROSType in library");`
A common thread for the messages throwing this error is that they all contain the same custom types in multiple sub-entries. The result is that the reverse parsing of messages is not sufficient to capture all dependencies. 
This PR suggests creating all the known types the first time through the messages and then filling in the packages only after. It is slightly less efficient, but correctly captures dependencies (as far as I can tell).

[bugfix] fix parsing of custom types added multiple times in messages

---

plotjuggler_app/mainwindow.cpp

update the reactive scripts on playback loop. previously on moving manually the timeslider updated them.
PS: thanks for this amazing tool, I use it everyday!

Update Reactive Scripts on playback loop

---

plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp

- Closes #778
- Change order of deletion for dialogs.
- First delete child dialog `_dateTime_dialog` then parent `_dialog`.
Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

Fix for segfault in DataLoadCSV destructor

---

snap/snapcraft.yaml

Installed plotjuggler via snap in ubuntu 20.04
Noticed that, when importing a large protobuf message which depends on google/protobuf, I got the following error 
```
google/protobuf/descriptor.proto: File not found
```
I assumed this was just a problem of needing to reference the path to these protos. However, this path selection through the plotjuggler GUI was unsuccessful.
Google'd the problem and found [this discussion](https://github.com/grpc-ecosystem/grpc-gateway/issues/422) which yielded the result of installing apt package `libprotobuf-dev`. Once this was installed, I did not need to add anything to my protobuf path to get the import to work.
I should probably dig deeper to figure out _why_ this package was needed instead of just `libprotobuf17`, but figured the solution might be …

Support Protos That Reference Google/Protobuf

---

plotjuggler_app/mainwindow.cpp

This is a pretty obscure fix. But it can give new users a negative impression. Triggering the bug goes like this:
1. Either on a machine that has never run PJ or if you delete the preferences file (platform dependent: mac -> delete $HOME/.config/PlotJuggler/PlotJuggler-3.ini)
2. Start PJ
3. Go App -> Preferences
4. Click "Cancel"
5. The UI goes all weird, log states "QIODevice::read (QFile, ":/resources/stylesheet_.qss"): device not open"

Fix for missing preferences

---

plotjuggler_plugins/DataLoadParquet/CMakeLists.txt

The actual path to the shared library is in `${PARQUET_SHARED_LIB}` instead of in `${PARQUET_LIBRARIES}`.
Fixes #789

Fix the bug where the shared library Parquet is not linked

---

COMPILE.md

Taken from CI: https://github.com/facontidavide/PlotJuggler/blob/main/.github/workflows/ubuntu.yaml#L20-L31
I tried to build the package from source with those instructions and needed to update the commands. I guess Ubuntu 18.04 has EOL 30 of April, so these instructions would be more useful updated?
Note that in https://github.com/PlotJuggler/plotjuggler-ros-plugins on the ros2 branches the instructions still say `catkin build` instead of `colcon build`. That may need an update too :)

Updating COMPILE dependencies to install

---

plotjuggler_app/resources/default.snippets.xml

The only option available previously was "backward difference". This gives a new option which can help reduce noise. Here's a wikipedia article on the difference:  https://en.wikipedia.org/wiki/Finite_difference
Here's a comparison plot from an actual robot. The top plot is arm commands, the middle plot is backward derivative, the bottom plot is central derivative. You can see it's less noisy than the middle one.

Add a "central difference" method of derivative calculation

---

snap/snapcraft.yaml

Due to `libzstd` missing Plotjuggler was not building the `MCAP` plugin in the snap.
Partially solve: https://github.com/facontidavide/PlotJuggler/issues/783

fix(snap): add libzstd for mcap support

---

plotjuggler_app/mainwindow.cpp

If a plugin throws an exception, it crashes the main app. With this change, the exception is caught, and the throwing plugin is skipped so that the main app can continue its regular operation with the remaining plugins.
When the ROS2 plugins are being loaded without sourcing the ROS2 itself, the output after the proposed changes is as follows. Usually, this case should not be applicable, but I ran into it while I was playing with building an AppImage, and wanted to make a PR.
> ...
"libDataStreamROS2.so: skipping, because it throwed the following exception:"
"failed to initialize rcl init options: failed to get symbol 'rmw_init_options_init' due to Environment variable 'AMENT_PREFIX_PATH' is not set or empty, at ./src/functions.cpp:171, at ./src/rcl/init_options.c:75"
... …

Prevent runtime_error exceptions of plugins from crashing the main app

---

plotjuggler_plugins/DataStreamMQTT/mqtt_test_proto.py
plotjuggler_plugins/DataStreamMQTT/robot_state.proto
plotjuggler_plugins/DataStreamMQTT/robot_state_pb2.py
plotjuggler_plugins/ParserProtobuf/protobuf_parser.cpp

Hi,
Currently protobuf maps are treated as a list of repeated messages where the name of the series is the index in the list of repeated messages. Unfortunately, the order of the entries in the map is not stable, and could change over time -- as a result, we end up with a single series effectively containing a random set of map entry, which is not so useful for plotting!
This change detect protobuf maps and uses the "key" in the series name instead of just the index allowing us to plot protobuf map data!
I added an example of this to the MQTT publisher and used that to test this change.
I'm happy to make any other changes to help add this feature, thank you!

Handle protobuf maps

---

.dockerignore
COMPILE.md
Dockerfile
appimage/AppImage.sh

* Revise the Dockerfile to successfully compile PlotJuggler with MQTT & ZMQ plugins
* Adds a script to compile an AppImage from within the docker environment; this will also work standalone
`docker buildx build -o . .` results a in `PlotJuggler-x86_x64.AppImage` which has been tested to have a working MQTT client via mosquitto

Add support for building AppImage via docker

---

plotjuggler_base/include/PlotJuggler/special_messages.h
plotjuggler_plugins/DataLoadULog/ulog_parser.h

Plotjuggler's fails to build on my machine. There seems to be a missing include of cstdint.
```
λ g++ --version
g++ (GCC) 13.1.1 20230429
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
[  0%] Automatic MOC and UIC for target plotjuggler_base
[  0%] Automatic MOC and UIC for target lz4_static
[  0%] Automatic MOC and UIC for target plotjuggler_qwt
[  0%] Automatic MOC and UIC for target plotjuggler_qwt_objects
[  0%] Automatic MOC and UIC for target lua_static
[  0%] Automatic MOC and UIC for target QCodeEditor
[  0%] Automatic MOC and UIC for target colorwidgets
[  0%] Automatic MOC and UIC for target qt_advanced_docking
[  0%] …
```

Add missing cstdint include

---

plotjuggler_plugins/ParserProtobuf/protobuf_parser.cpp

Here in `ProtobufParser::parseMessage()` we allocate with no further deallocation:
```
google::protobuf::Message* mutable_msg = prototype_msg->New();
```

Fix memory leak in protobuf parser

---

plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp
plotjuggler_plugins/DataLoadCSV/dataload_csv.ui

Add 'tab' as a separator in the CSV loader

---

CMakeLists.txt

The current approach doesn't work in our build system, since you need `find_package(catkin QUIET)` to fire. The other env vars aren't set in our build. I believe this method should be a little more bulletproof, and works fine on our build of https://github.com/BehaviorTree/BehaviorTree.CPP.

Use a more reliable method to select buildtool

---

.github/workflows/snap.yaml

I am very sorry I missed that line when preparing the core22 snap workflow. 
Note that the store credentials need a refresh as described in https://github.com/facontidavide/PlotJuggler/actions/runs/6254336114/job/16982529217
```
Exported credentials are no longer valid for the Snap Store.
Recommended resolution: Run export-login and update SNAPCRAFT_STORE_CREDENTIALS.
For more information, check out: https://snapcraft.io/docs/snapcraft-authentication
```
So even with this fix the above secret has to be taken care of by @facontidavide directly in the secrets.STORE_LOGIN

Fix missing '22' in the new snap core22 workflow

---

plotjuggler_app/plotwidget.cpp
plotjuggler_app/plotwidget_editor.cpp
plotjuggler_app/plotwidget_editor.h
plotjuggler_app/plotwidget_editor.ui
plotjuggler_base/include/PlotJuggler/plotwidget_base.h
plotjuggler_base/src/plotwidget_base.cpp

As requested by issue #866. Step-wise interpolation between points (already supported by qwt).

Add "Steps" when drawing curves

---

plotjuggler_plugins/DataStreamUDP/udp_client.py
plotjuggler_plugins/DataStreamUDP/udp_server.cpp
plotjuggler_plugins/DataStreamUDP/udp_server.ui

This adds the ability to specify a address other than 127.0.0.1 when starting DataStreamUDP.  If the address is a multicast address the UDP socket is configured to join the multicast group.

Add multicast support to DataStreamUDP.

---

plotjuggler_plugins/ParserROS/ros_parser.cpp

With the current version, DataLoadRos2 throws a "Not Enough Memory in the Buffer Stream" Error when Loading
a `diagnostic_msgs/DiagnosticStatus.msg` from a rosbag.
This is IMO caused by typo while creating the specialized ros parsers. In there, the DiagnosticArray is mixed up with up the DiagnosticStatus message. As a result, the diagnostic status is tried to be deserialized as DiagnosticArray, which throws the aforementioned Exception.
Switching to the correct msg type fixes the issue for me.

BUGFIX: Parsing of Diagnostic Status Msg

---

plotjuggler_app/plotwidget_editor.cpp

On selecting the relatively new curve style "Steps(Post)," the style was correctly applied to the plot.
However, on reopening the "Edit the Plot Area" dialog, the radio button wrongly showed that the curve style "Steps(Pre)" would be selected. 
This problem is fixed with this PR.
Everything else already worked correctly beforehand. The correct curve style was applied and also saved in the layout.
Just the preselection of the radio buttons was wrong.
Hopefully, my description is clear enough!

Bugfix: Wrong curvestyle is preselected

---

plotjuggler_plugins/ParserROS/rosx_introspection/src/ros_message.cpp

In some scenarios for msg types defined with fields of types with the same type name as types that exist in other packages, the type will be resolved to a package which is not that of the root type containing the field. As an example:
`motion_msgs/Motion` defined as:
```
uint8 type
float64 start_time
float64 duration
Point start_point
Point end_point
etc..
```
The `Point` in this type is part of our `motion_msgs` package and thus is referred to without a package name. When being deserialized it current is resolved to `geometry_msgs/Point` instead of `motion_msgs/Point`, resulting in a size mismatch and overrun further into deserializing the msg.
The change in the PR would check for the existence of a `Point` type with the same package as `motion_msgs/Motion`, matching `motion_msgs/Point` …

Bugfix: Guess ROS msgs types within package before selecting external to package type

---

CMakeLists.txt
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/Cdr.h
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/CdrEncoding.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/CdrSizeCalculator.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/FastBuffer.h
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/FastCdr.h
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/cdr/fixed_size_string.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/config.h.in
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/detail/container_recursive_inspector.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/eProsima_auto_link.h
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/exceptions/BadOptionalAccessException.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/exceptions/BadParamException.h
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/exceptions/Exception.h
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/exceptions/LockedExternalAccessException.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/fastcdr_dll.h
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/xcdr/MemberId.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/xcdr/detail/optional.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/xcdr/external.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/include/fastcdr/xcdr/optional.hpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/CMakeLists.txt
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/Cdr.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/CdrSizeCalculator.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/FastBuffer.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/FastCdr.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/exceptions/BadOptionalAccessException.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/exceptions/Exception.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/exceptions/LockedExternalAccessException.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/src/cpp/exceptions/NotEnoughMemoryException.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/src/deserializer.cpp

Resolve: #919 #861 
I would like to be able to use PlotJuggler with the latest fast-CDR from eProsima which is why I propose:
- Update local thirdparty files from eProsima to version 2.x.x
- Update cmake version so that it is possible to compile with fastcdr installed on the dev machine.
Tested with eProsima helloword example: Ok
Helloworld example: https://fast-dds.docs.eprosima.com/en/latest/fastdds/getting_started/simple_app/simple_app.html
Configuration file: https://plotjuggler-fastdds-plugins.readthedocs.io/en/latest/rst/user_manual/configuration.html
configuration file to be able to read from a Topic:
```
<types>
<type>
<struct name="HelloWorld">
<member name="index" type="uint32"/>
<member name="message" type="string"/>
</struct>
</type>
</types>
```
tested on:
``` 
Static …
```

PlotJuggler with Fast-CDR-2.x.x

---

plotjuggler_plugins/ParserROS/ros_parser.cpp

Without this fix, parsing of JointState messages is broken if `velocity` or `effort` fields are empty (which is allowed in the message definition).

Fixed parsing JointState messages

---

plotjuggler_plugins/PluginsZcm/dataload_zcm.cpp

This commit adds support for zcm messages that are empty. Before the messages would just be dropped and not displayed in PlotJuggler. Now they will show up at the correct timestamp with no contents and a numeric value of 0 for each message that exists

Added support for empty messages

---

CMakeLists.txt
COMPILE.md

Necessary work to build from source code on macos 14.2.1 (and most likely newer and older). 
This PR also solves https://github.com/facontidavide/PlotJuggler/issues/897

Added ZeroMQ and updated docs

---

snap_core22/snapcraft.yaml

The msg `ros-humble-dataspeed-dbw-msgs` got removed.
Trying to install this message in the core22 snap will fail.
https://discourse.ros.org/t/new-packages-and-patch-release-for-humble-hawksbill-2024-05-23/37872#removed-packages-4-4

fix(snap_core22): ros-humble-dataspeed-dbw-msgs has been removed

---

plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/CMakeLists.txt

The tests were not imported but still referenced in the cmake depending on the system cmake version.
My build (Debian testing, ROS-O)  just got stuck on:
```
CMake Error at plotjuggler_plugins/ParserROS/rosx_introspection/3rdparty/Fast-CDR/CMakeLists.txt:136 (add_subdirectory):
add_subdirectory given source "test" which is not an existing directory.
```
It looks like you imported the library without its tests, but did not remove the cmake reference.

[ROS-O] drop broken test hook from Fast-CDR import

---

plotjuggler_plugins/DataStreamUDP/udp_server.cpp

UDP server dialogue crashes when theres no protocol stored in settings, as the default is wrongly "JSON", but it should be "json".
This patch uses default "json" even when there is wrong protocol in settings to prevent further crashes.
Fixes #992

udp_server: fix crash when dialog opens for the first time

---

installer/io.plotjuggler.application/meta/installscript.qs
installer/io.plotjuggler.application/meta/package.xml
installer/io.plotjuggler.application/meta/targetwidget.ui

Currently, when installing PlotJuggler, the installer simply fails when an existing installation is present. This modification to the Qt Installer Framework installer is based on StackOverflow answers by [rationalcoder](https://stackoverflow.com/a/46614107), [Skeird](https://stackoverflow.com/a/66154201), and [chipolux](https://stackoverflow.com/a/73819557) addressing this use-case of Qt Installer Framework's offline installer.
When an existing installation is detected, the installer now merely displays a message stating "Existing installation detected and will be overwritten". By calling the `maintenancetool.exe`, the installation is not merely overwritten, but the previous installation is properly uninstalled, too.

Windows Installer: Added ability to detect and uninstall existing installations when detected

---

plotjuggler_plugins/DataStreamMQTT/mqtt_client.cpp
plotjuggler_plugins/DataStreamMQTT/mqtt_client.h

This pull request fixes issues #1006 and #1008.
On Linux the MQTT plugin freezes PlotJugger see issue #1008. The program flow seems to be stuck within mosquitto_connect_bind_v5() on the second connection attempt. This is solved by starting with a fresh mosquitto instance at each connection attempt.
On Windows PlotJuggler doesn't show any topics after establishing a connection, see issue #1006. mqtt_client.cpp does not check the return code of mosquitto_loop_start(), which may return MOSQ_ERR_NOT_SUPPORTED on Windows. This causes the plugin to assume that the connection has been established, but in reality the mosquitto event loop is not processed. This causes the user to think that a connection was established but no topics are displayed. The plugin worked in the past with no recent …

Fix MQTT plugin (#1006, #1008)

---

plotjuggler_plugins/DataLoadParquet/dataload_parquet.cpp

When parquet parser encounters an 'invalid' columns it should skip it in the stream.

fix broken parquet parsing when parquet file contains 'invalid' columns

---

plotjuggler_plugins/DataLoadULog/ulog_parser.cpp
plotjuggler_plugins/DataLoadULog/ulog_parser.h

The previous parsing assumed that the timestamp for a ulog data series was always at index 0, which is often, but not necessarily the case. The parser now store the correct index when parsing the definition.

fix(ulog): the index of the timestamp may be non-zero

---

plotjuggler_plugins/DataLoadMCAP/dataload_mcap.cpp
plotjuggler_plugins/DataLoadMCAP/dataload_params.h
plotjuggler_plugins/DataLoadMCAP/dialog_mcap.cpp
plotjuggler_plugins/DataLoadMCAP/dialog_mcap.ui

The DataLoadMCAP plugin support only the publishTime of the mcap message. Add a radio button in the load dialog to select the logTime or publishTime.

DataLoadMCAP: add support to mcap logTime

---

plotjuggler_plugins/DataStreamZMQ/datastream_zmq.cpp
plotjuggler_plugins/DataStreamZMQ/datastream_zmq.h
plotjuggler_plugins/DataStreamZMQ/utilities/start_test_publisher.py

Good evening,
I have done what you suggested on the last pull request, it was closed so I guess I have to open a new one.
The pre-commit passed and the changes should be backward compatible from my tests. I will paste what the same message I had on the previous pull request.
Topic support was present, but did not ground incoming messages in said topics, resulting in overriding duplicate keys (e.g., the timestamp). In addition, no multipart messages were used, making it difficult to actually use it with a real PUB/SUB structure.
I propose the following update to the plugin.
The plugin now can receive a two-part message, the first part is the topic (as string) and the second is the payload (the data you said PlotJuggler to expect).
Using the topic as a key to a map of parsers, it maps …

ZMQ plugin improvements

---

3rdparty/CMakeLists.txt
COMPILE.md

Hi, @facontidavide!  😃  I was just now trying to build PlotJuggler on my MacBook Air M2 from source, and I ran into a few issues. This PR includes the changes I had to make to build it successfully.
Note: this bumps the `ThePhD/sol2` dependency from `v3.3.0` to `v3.5.0`.

Update macOS compile instructions

---

.gitignore
plotjuggler_plugins/DataStreamUDP/udp_client.py
plotjuggler_plugins/DataStreamUDP/udp_server.cpp

Trying IPv6 multicast, I could get nothing to work. After much trial & error, I got this solution working, including using the `udp_client.py` tool as a test data source with the documented multicast groups for both IPv4 and IPv6. I noticed the previous #858, @agoessling would you like to re-test your use-case?

Fix IPv6 multicast

---

plotjuggler_app/statistics_dialog.cpp
plotjuggler_app/statistics_dialog.h
plotjuggler_app/statistics_dialog.ui

It's nice to know at a glance the rate of which a topic is logged

statistics: add avg interval

---

plotjuggler_app/CMakeLists.txt

At least mold complains when trying to build without explicitly linking roscpp (when required).
```
mold: error: undefined symbol: ros::removeROSArgs(int, char const* const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)
>>> referenced by main.cpp
>>>               CMakeFiles/plotjuggler.dir/main.cpp.o:(main)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm not sure what you will do with this patch after you merged https://github.com/PlotJuggler/plotjuggler-ros-plugins/pull/98 recently.
It would be great if you could provide some guidance on how ROS-O should handle PlotJuggler in the future.

fix linking to roscpp when required

---

.github/workflows/snap_core22.yaml
snap_core22/snapcraft.yaml

This PR fixes the core22 snap build to align with recent changes in the project's installation.
The snap required some changes in the CMakelists.txt due to latest changes in the project installation settings.
The keys fixes are:
- Enable flag `DBASE_AS_SHARED=ON` to compile plotjuggler_base as shared.
- Add the `NAMESPACE` keyword to the `install(EXPORT) `(when not building with ament) to properly set up namespace for exported targets (e.g. plotjuggler::plotjuggler_base) needed by the `plotjuggler-ros-plugins` package.
- Add `include(CMakeFindDependencyMacro)` in the cmake config because of `find_dependency(...)`. Without this, the cmake pluging fails to find the macro.
These changes mirror what is already handled internally when building in an ament (ROS) context.
This PR pins snapcraft …

Fix core22 snap

---

plotjuggler_plugins/ParserProtobuf/error_collectors.cpp
plotjuggler_plugins/ParserProtobuf/error_collectors.h

This PR fixes the compilation with recent protobuf version, while keeping compatibility with older protobuf versions.
Fix https://github.com/facontidavide/PlotJuggler/issues/1004 .
Fix https://github.com/facontidavide/PlotJuggler/pull/1097 .
Fix https://github.com/facontidavide/PlotJuggler/pull/1106 .
Related to https://github.com/facontidavide/PlotJuggler/issues/1090#issuecomment-3025267144 .

Fix compilation with recent protobuf

---

plotjuggler_app/CMakeLists.txt

Otherwise catkin install workspaces include everything except for the expected binary.

provide install rule again from catkin build

---

plotjuggler_plugins/DataLoadULog/dataload_ulog.cpp
plotjuggler_plugins/DataLoadULog/ulog_parser.cpp
plotjuggler_plugins/DataLoadULog/ulog_parser.h

fixes: https://github.com/facontidavide/PlotJuggler/issues/1136
The timestamp field is [optional](https://github.com/facontidavide/PlotJuggler/issues/1136#issuecomment-3191710284), so in case there is no timestamp, just a fixed increment.

fix(ulog_parser): allow messages without timestamp field

---

.github/workflows/debian.yaml

fixes the uploading of the artifacts, without this the file can not be found in the release upload

CI: rename .deb file before uploading

---

plotjuggler_app/resources/default.snippets.xml

The default `quat_to_yaw` and `quat_to_roll` custom series are using a two argument atan method, but this was only added in lua 5.3. If two arguments are provided in older versions the second argument is ignored and the regular `atan(x)` method is called, which computes the wrong value. As far as I can tell plotjuggler just uses whatever version of lua is available in the system, and so doesn't guarantee it's >=5.3 https://github.com/facontidavide/PlotJuggler/blob/e9e2e624d67cc157143f42342d916c0abe38a487/cmake/find_or_download_lua.cmake#L5
but at least the ROS humble release of this is depending on liblua5.1.0
```
matt@matt-thinkpad:~$ apt show ros-humble-plotjuggler
Package: ros-humble-plotjuggler
Version: 3.10.11-1jammy.20250727.225740
Priority: optional
Section: misc
Maintainer: Davide …
```

Fix atan bug in lua `quat_to_yaw` and `quat_to_roll` conversions for lua versions <5.3

---

plotjuggler_plugins/ParserROS/rosx_introspection/include/rosx_introspection/contrib/nanocdr.hpp

Yes, this function must not be constexpr, but it's also defined in a header included in multiple translation units, so it must be `inline` to avoid multiple implementations for the function:
> /usr/bin/ld: CMakeFiles/rosx_introspection.dir/src/serializer.cpp.o: in function `nanocdr::getCurrentEndianness()':
./.obj-x86_64-linux-gnu/plotjuggler_plugins/ParserROS/rosx_introspection/./plotjuggler_plugins/ParserROS/rosx_introspection/include/rosx_introspection/contrib/nanocdr.hpp:336: multiple definition of `nanocdr::getCurrentEndianness()'; CMakeFiles/rosx_introspection.dir/src/deserializer.cpp.o:./.obj-x86_64-linux-gnu/plotjuggler_plugins/ParserROS/rosx_introspection/./plotjuggler_plugins/ParserROS/rosx_introspection/include/rosx_introspection/contrib/nanocdr.hpp:336: first defined here …

Fix copilot breakage
