facontidavide/PlotJuggler

README.md
docs/visualization_howto.md

Minor style fixes (couldn't resist either).

Update README.md & docs

---

CMakeLists.txt
plugins/DataStreamServer/CMakeLists.txt
plugins/DataStreamServer/DataStreamClientSample/client.cpp
plugins/DataStreamServer/DataStreamClientSample/client.h
plugins/DataStreamServer/DataStreamClientSample/client.pro
plugins/DataStreamServer/DataStreamClientSample/main.cpp
plugins/DataStreamServer/datastreamserver.cpp
plugins/DataStreamServer/datastreamserver.h

Hello,
I wrote a small simple plugin based on your sample.
It allow any third party application to connect to Plotjuggler using websocket and push their values.
I though it could be usefull to others.

A small plugin creating a websocket server

---

plugins/DataStreamServer/CMakeLists.txt

I had some case error I missed because I worked on Windows, here is the fixed #64

Fixed case errors

---

plugins/DataStreamWebSocket/datastreamserver.cpp
plugins/DataStreamWebSocket/datastreamserver.h

when I use `catkin_make` to build this project,an error occurs.

Virtual Override bug

---

3rdparty/qwt/src/qwt_null_paintdevice.cpp
3rdparty/qwt/src/qwt_painter.cpp
3rdparty/qwt/src/qwt_painter_command.h
3rdparty/qwt/src/qwt_picker.cpp
3rdparty/qwt/src/qwt_plot_canvas.cpp
3rdparty/qwt/src/qwt_plot_curve.cpp
3rdparty/qwt/src/qwt_plot_panner.cpp
3rdparty/qwt/src/qwt_plot_renderer.cpp
3rdparty/qwt/src/qwt_widget_overlay.cpp

add qtpainterpath.h

---

3rdparty/Qt-Advanced-Docking/CMakeLists.txt

Apply #361 again to fix #353
Commit got lost somehow ..
/cc @tomjakubowski

Apply #361 again to fix #353

---

.gitmodules
CMakeLists.txt
plugins/DataStreamLSL/CMakeLists.txt
plugins/DataStreamLSL/datastream_lsl.cpp
plugins/DataStreamLSL/datastream_lsl.h
plugins/DataStreamLSL/datastream_lsl.ui
plugins/DataStreamLSL/datastream_lsl2.ui
plugins/DataStreamLSL/lsl_publisher.py
plugins/DataStreamLSL/streamer.cpp
plugins/DataStreamLSL/streamer.h
src/resources/stylesheet_light.qss

Dear Davide,
This pull request contains the LSL (https://github.com/sccn/liblsl) plugin. 
The plugin queries LSL stream in a local network, then behaves as a relay that passes data to PlotJuggler. 
We developed this on a weekend project. See below for the contributors:
- Celal Savur (@csavur)
- Shitij Kumar (@spk4422)
- Mazin Ali (@mazinMS)
Please let me if you have any questions.

LabStreamlayer (LSL) plugin is developed.

---

src/mainwindow.cpp

Fixed message_parser plugin loading segfault

---

plugins/DataStreamLSL/datastream_lsl.cpp
plugins/DataStreamLSL/datastream_lsl.ui

LAG:
- Time out added when App resolving streams.
CRASH:
- When the LSL plugin starts and stops, it causes a crash. The reason for the crash was that stream was a null pointer.

Lag and crash fixed

---

plotjuggler_app/preferences_dialog.ui

`Appearence` -> `Appearance`.
😄

fix typo in preferences dialog

---

CMakeLists.txt

This commit just adds a new directory into the apple validation in CMakeLists.txt.
https://github.com/facontidavide/PlotJuggler/issues/517

Homebrew path added into CMakeLists #517

---

plotjuggler_app/mainwindow.ui

Add tooltip text to the Zoom Out All button.

Add tooltip to the zoom out button

---

plotjuggler_app/mainwindow.ui

Increase playbackStep number of decimal to three, allowing down to 1ms time increment.

increase playback step precision

---

CMakeLists.txt
COMPILE.md
README.md
conanfile.txt
plotjuggler_plugins/DataLoadParquet/CMakeLists.txt
plotjuggler_plugins/DataStreamMQTT/CMakeLists.txt
plotjuggler_plugins/DataStreamMQTT/cmake/Findmosquitto.cmake
plotjuggler_plugins/DataStreamZMQ/CMakeLists.txt
plotjuggler_plugins/DataStreamZMQ/cmake/FindZeroMQ.cmake
plotjuggler_plugins/ParserProtobuf/CMakeLists.txt
vcpkg.json

Improve windows compilation with vcpkg and conan

Better cmake

---

plotjuggler_app/main.cpp
plotjuggler_app/mainwindow.cpp

Useful for https://github.com/commaai/PlotJuggler/issues/49

Add support for custom window titles

---

COMPILE.md

Hey!
I've added Mac compilation section and fixed some minor typos.

Add mac compilation section

---

.gitignore
plotjuggler_app/mainwindow.cpp
plotjuggler_app/mainwindow.h

- Add drag n drop functionality
- Check if manually provided plugin name is enabled
- Update `.gitignore`
- Run `clang-format`
And thanks for inspiration: https://github.com/facontidavide/PlotJuggler/pull/454

Add Drag n Drop

---

3rdparty/QCodeEditor/src/internal/QCSVHighlighter.cpp

Added per https://github.com/facontidavide/PlotJuggler/issues/732

Add MIT license notice to QCodeEditor addition

---

plotjuggler_plugins/DataLoadParquet/dataload_parquet.ui

A link to QTime format string was there, but not QDate

Add link to QDate format string

---

plotjuggler_plugins/DataStreamMQTT/mqtt_dialog.cpp
plotjuggler_plugins/ParserProtobuf/CMakeLists.txt

Minor typo fixes (x2)

---

plotjuggler_app/curvelist_panel.cpp
plotjuggler_app/customtracker.cpp
plotjuggler_app/preferences_dialog.cpp
plotjuggler_app/preferences_dialog.ui

Added float precision in settings

Feature: add float precision setting

---

.pre-commit-config.yaml
CHANGELOG.rst
CMakeLists.txt
README.md
package.xml
plotjuggler_app/cheatsheet/cheatsheet_dialog.ui
plotjuggler_app/mainwindow.cpp
plotjuggler_app/preferences_dialog.ui
plotjuggler_app/transforms/first_derivative.ui
plotjuggler_app/transforms/function_editor.ui
plotjuggler_app/transforms/integral_transform.ui
plotjuggler_app/transforms/scale_transform.ui
plotjuggler_base/include/PlotJuggler/plotdata.h
plotjuggler_base/include/PlotJuggler/statepublisher_base.h
plotjuggler_base/include/PlotJuggler/stringseries.h
plotjuggler_base/src/timeseries_qwt.h
plotjuggler_plugins/DataStreamZMQ/zmq.hpp
plotjuggler_plugins/ParserROS/ros_parser.cpp
plotjuggler_plugins/ParserROS/rosx_introspection/include/rosx_introspection/ros_parser.hpp
plotjuggler_plugins/PluginsZcm/dataload_zcm.cpp
plotjuggler_plugins/PluginsZcm/datastream_zcm.cpp
plotjuggler_plugins/ToolboxLuaEditor/lua_editor.ui
snap_core22/snapcraft.yaml
tools/.codespell_ignore_words
tools/pyproject.toml

* I have added `codespell` as a pre-commit hook.
* In addition, I have added a [pyproject.toml](https://github.com/facontidavide/PlotJuggler/compare/main...leander-dsouza:PlotJuggler:add_codespell?expand=1#diff-34e90ee5f36843fb20583311fd7c4b5323270afe4277793801cad4c54e8abb67) file outlining the configuration of future hooks to come. This is inspired by [Nav2's](https://github.com/ros-navigation/navigation2/blob/main/tools/pyproject.toml) current setup.
* Install pre-commit:
```bash
sudo apt install pre-commit
```
* Install pre-commit in the repository:
```bash
cd PlotJuggler
pre-commit install
```
* Run pre-commit across all files:
```bash
pre-commit run --all-files
```

Added codespell as a pre-commit hook.

---

plotjuggler_app/curvelist_panel.cpp
plotjuggler_app/curvelist_panel.h
plotjuggler_app/curvelist_panel.ui

Add button to delete custom timeseries
